project_id = "qeejuomcapbdlhnjqjcc"

[functions.telegram-bot]
verify_jwt = false

[functions.setup-telegram-webhook]
verify_jwt = false

[functions.debug-bot]
verify_jwt = false

[functions.test-webhook]
verify_jwt = false

[functions.binance-pay-checkout]
verify_jwt = false

[functions.binance-pay-webhook]
verify_jwt = false

[functions.setup-webhook]
verify_jwt = false

[functions.cleanup-old-sessions]
verify_jwt = false

[functions.cleanup-old-receipts]
verify_jwt = false

[functions.analytics-data]
verify_jwt = false

[functions.reset-bot]
verify_jwt = false

[functions.test-bot-status]
verify_jwt = false

[functions.ai-faq-assistant]
verify_jwt = false

[functions.trade-helper]
verify_jwt = false

[functions.ocr-worker]
verify_jwt = false

[functions.payment-notifier]
verify_jwt = false
