name: Assets Audit

on:
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Run assets audit (dry-run)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: bash scripts/cleanup/report.sh

  # Optional job to perform deletion only on manual dispatch with label:
  # (Keep disabled unless you really want automation)
