name: Bot Health Checks
on:
  workflow_dispatch:
  pull_request:
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tools
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Install Supabase CLI
        run: bash scripts/env/install_supabase_cli.sh
      - name: Run health checks
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: bash scripts/bot/health_check.sh
