name: TypeScript Check
on:
  push:
  pull_request:
jobs:
  deno-ts-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Cache Deno deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts', 'deno.json') }}
      - name: Typecheck
        run: |
          chmod +x scripts/typecheck.sh
          deno task typecheck
