name: Bot & MiniApp Verification
on:
  pull_request:
  workflow_dispatch:
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y jq
      - name: Run verification
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        run: bash scripts/verify/verify_all.sh
      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: verify-report
          path: .out/verify_report.md
